# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_auto_20160410_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='nextReminder',
            new_name='next_reminder',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='smsVerifyCode',
            new_name='sms_verify_code',
        ),
    ]
