# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0004_auto_20160408_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='smsVerifyCode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
