# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-22 02:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0004_auto_20160721_2255'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Betas',
            new_name='Beta',
        ),
    ]
