# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-22 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0005_auto_20160721_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='beta',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
